---
- name: Reload SystemD daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable etcd service
  ansible.builtin.systemd_service:
    name: etcd
    enabled: true

- name: Restart etcd service
  ansible.builtin.systemd_service:
    name: etcd
    state: restarted
