---
- name: Create Kubernetes controller manager certificates
  tags: cert
  ansible.builtin.include_tasks:
    file: cert.yml
    apply:
      tags: cert
      become: false
      delegate_to: localhost

- name: Configure Kubernetes controller manager
  tags: config
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags: config
      notify:
        - Reload SystemD daemon
        - Enable Kubernetes controller manager service
        - Restart Kubernetes controller manager service
