---
# Subject details for the etcd CA certificate.
etcd_cert_ca_subject:
  CN: Waverly etcd CA

# Duration of etcd CA certificate validity.
etcd_cert_ca_duration: 3650d

# Subject details for the etcd client certificate.
etcd_cert_entity_client_subject:
  CN: client.etcd

# Subject Alternative Names for the etcd client certificate.
etcd_cert_entity_client_san:
  # Local
  - IP:127.0.0.1
  - DNS:localhost

# Duration of etcd client certificate validity.
etcd_cert_entity_client_duration: 1825d

# Subject details for the etcd server certificate.
etcd_cert_entity_server_subject:
  CN: server.etcd

# Subject Alternative Names for the etcd server certificate.
etcd_cert_entity_server_san:
  # Local
  - IP:127.0.0.1
  - DNS:localhost

  # Node-specific
  - "IP:{{ nebula_cert_entity_host_ip | ansible.utils.ipaddr('address') }}"
  - "DNS:{{ etcd_config_member_name }}.server.etcd"

# Duration of etcd server certificate validity.
etcd_cert_entity_server_duration: 1825d

# Subject details for the etcd peer certificate.
etcd_cert_entity_peer_subject:
  CN: peer.etcd

# Subject Alternative Names for the etcd peer certificate.
etcd_cert_entity_peer_san:
  # Local
  - IP:127.0.0.1
  - DNS:localhost

  # Node-specific
  - "IP:{{ nebula_cert_entity_host_ip | ansible.utils.ipaddr('address') }}"
  - "DNS:{{ etcd_config_member_name }}.peer.etcd"

# Duration of etcd peer certificate validity.
etcd_cert_entity_peer_duration: 1825d
