---
- name: Create etcd directories
  loop:
    - path: "{{ etcd_config_dir }}"
      mode: "0755"
    - path: "{{ etcd_config_data_dir }}"
      mode: "0755"
    - path: "{{ etcd_config_cert_dir }}"
      mode: "0700"
  loop_control:
    label: "{{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: directory
    owner: root
    group: root

- name: Copy etcd cert certificates
  loop:
    - label: CA certificate
      src: "{{ (etcd_cert_ca_local_dir, 'ca.crt') | ansible.builtin.path_join }}"
      dest: "{{ (etcd_config_cert_dir, 'ca.crt') | ansible.builtin.path_join }}"
      mode: "0644"
    - label: Peer certificate
      src: "{{ (etcd_cert_entity_local_dir, inventory_hostname, 'peer.crt') | ansible.builtin.path_join }}"
      dest: "{{ (etcd_config_cert_dir, 'peer.crt') | ansible.builtin.path_join }}"
      mode: "0644"
    - label: Peer private key
      src: "{{ (etcd_cert_entity_local_dir, inventory_hostname, 'peer.key') | ansible.builtin.path_join }}"
      dest: "{{ (etcd_config_cert_dir, 'peer.key') | ansible.builtin.path_join }}"
      mode: "0600"
    - label: Server certificate
      src: "{{ (etcd_cert_entity_local_dir, inventory_hostname, 'server.crt') | ansible.builtin.path_join }}"
      dest: "{{ (etcd_config_cert_dir, 'server.crt') | ansible.builtin.path_join }}"
      mode: "0644"
    - label: Server private key
      src: "{{ (etcd_cert_entity_local_dir, inventory_hostname, 'server.key') | ansible.builtin.path_join }}"
      dest: "{{ (etcd_config_cert_dir, 'server.key') | ansible.builtin.path_join }}"
      mode: "0600"
  loop_control:
    label: "{{ item.label }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root

- name: Render etcd configuration template
  ansible.builtin.template:
    src: etc/etcd/etcd.conf.yml.j2
    dest: "{{ etcd_config_file }}"
    mode: "0644"
    owner: root
    group: root
