---
- name: Download etcd
  tags: download
  become: false
  run_once: true
  delegate_to: localhost
  ansible.builtin.import_tasks: download.yml

- name: Install etcd
  tags: install
  ansible.builtin.import_tasks: install.yml

- name: Create etcd certificates
  tags: cert
  become: false
  delegate_to: localhost
  ansible.builtin.import_tasks: cert.yml

- name: Configure etcd
  tags: config
  notify:
    - Reload SystemD daemon
    - Enable etcd service
    - Restart etcd service
  ansible.builtin.import_tasks: config.yml
