---
- name: Download etcd
  tags: download
  ansible.builtin.include_tasks:
    file: download.yml
    apply:
      tags: download
      become: false
      run_once: true
      delegate_to: localhost

- name: Install etcd
  tags: install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: install

- name: Create etcd certificates
  tags: cert
  ansible.builtin.include_tasks:
    file: cert.yml
    apply:
      tags: cert
      become: false
      delegate_to: localhost

- name: Configure etcd
  tags: config
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags: config
      notify:
        - Reload SystemD daemon
        - Enable etcd service
        - Restart etcd service
