---
- name: Setup runc
  tags: runc
  ansible.builtin.include_tasks:
    file: runc/main.yml
    apply:
      tags: runc

- name: Setup CNI plugins
  tags: cni_plugins
  ansible.builtin.include_tasks:
    file: cni_plugins/main.yml
    apply:
      tags: cni_plugins

- name: Setup containerd
  tags: containerd
  ansible.builtin.include_tasks:
    file: containerd/main.yml
    apply:
      tags: containerd
