---
- name: Create Kubernetes API server certificates
  tags: cert
  ansible.builtin.include_tasks:
    file: cert.yml
    apply:
      tags: cert
      become: false
      delegate_to: localhost

- name: Configure Kubernetes API server
  tags: config
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags: config
      notify:
        - Reload SystemD daemon
        - Enable Kubernetes API server service
        - Restart Kubernetes API server service
