---
- name: Create host certificate directory
  ansible.builtin.file:
    mode: "0700"
    path: "{{ (kubernetes_kubelet_cert_entity_local_dir, inventory_hostname) | ansible.builtin.path_join }}"
    state: directory

- name: Create kubelet certificate
  block:
    - name: Create kubelet private key
      register: kubernetes_kubelet_cert_entity_private_key
      community.crypto.openssl_privatekey:
        path: "{{ (kubernetes_kubelet_cert_entity_local_dir, inventory_hostname, 'kubelet.key') | ansible.builtin.path_join }}"

    - name: Create kubelet certificate signing request
      register: kubernetes_kubelet_cert_entity_csr
      community.crypto.openssl_csr:
        path: "{{ (kubernetes_kubelet_cert_entity_local_dir, inventory_hostname, 'kubelet.csr') | ansible.builtin.path_join }}"
        privatekey_path: "{{ kubernetes_kubelet_cert_entity_private_key.filename }}"
        subject: "{{ kubernetes_kubelet_cert_entity_subject }}"
        subject_alt_name: "{{ kubernetes_kubelet_cert_entity_san }}"
        extended_key_usage: [serverAuth, clientAuth]

    - name: Sign kubelet certificate
      community.crypto.x509_certificate:
        path: "{{ (kubernetes_kubelet_cert_entity_local_dir, inventory_hostname, 'kubelet.crt') | ansible.builtin.path_join }}"
        provider: ownca
        csr_path: "{{ kubernetes_kubelet_cert_entity_csr.filename }}"
        ownca_path: "{{ kubernetes_cert_ca_certificate.filename }}"
        ownca_privatekey_path: "{{ kubernetes_cert_ca_private_key.filename }}"
        ownca_not_after: "+{{ kubernetes_kubelet_cert_entity_duration }}"
        ownca_not_before: "-1d"
