---
- name: Get latest Kubernetes version
  when: kubernetes_download_version == "latest"
  block:
    - name: Fetch latest Kubernetes release on GitHub
      register: kubernetes_download_github_release
      community.general.github_release:
        user: "{{ kubernetes_download_github_user }}"
        repo: "{{ kubernetes_download_github_repository }}"
        action: latest_release

    - name: Set Kubernetes version fact
      ansible.builtin.set_fact:
        kubernetes_download_version: "{{ kubernetes_download_github_release.tag | ansible.builtin.regex_replace('^v', '') }}"

- name: Link current version directory
  block:
    - name: Create version directory
      ansible.builtin.file:
        path: "{{ (kubernetes_download_local_dir, kubernetes_download_version) | ansible.builtin.path_join }}"
        mode: "0755"
        state: directory

    - name: Link current version directory
      ansible.builtin.file:
        src: "{{ (kubernetes_download_local_dir, kubernetes_download_version) | ansible.builtin.path_join }}"
        dest: "{{ kubernetes_download_current_local_dir_link }}"
        state: link

- name: Download Kubernetes binaries
  block:
    - name: Check if the Kubernetes archives already downloaded
      loop: "{{ kubernetes_download_architecture_map.items() }}"
      register: kubernetes_download_files
      loop_control:
        label: "{{ kubernetes_download_architecture[0] }}"
        loop_var: kubernetes_download_architecture
      ansible.builtin.stat:
        path: "{{ (kubernetes_download_current_local_dir_link, kubernetes_download_architecture[0]) | ansible.builtin.path_join }}"

    - name: Download Kubernetes archives
      when: not kubernetes_download_files.results[ansible_loop.index0].stat.exists
      loop: "{{ kubernetes_download_architecture_map.items() }}"
      loop_control:
        label: "{{ kubernetes_download_architecture[0] }}"
        loop_var: kubernetes_download_architecture
        extended: true
      ansible.builtin.get_url:
        url: "{{ kubernetes_download_url }}"
        dest: "{{ (kubernetes_download_current_local_dir_link, kubernetes_download_architecture[0]) | ansible.builtin.path_join }}"
        mode: "0644"
