---
- name: Download Kubernetes
  tags: download
  ansible.builtin.include_tasks:
    file: download.yml
    apply:
      tags: download
      become: false
      run_once: true
      delegate_to: localhost

- name: Install Kubernetes
  tags: install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: install

- name: Create Kubernetes certificates
  tags: cert
  ansible.builtin.include_tasks:
    file: cert.yml
    apply:
      tags: cert
      become: false
      delegate_to: localhost

- name: Setup Kubernetes API server
  tags: api_server
  ansible.builtin.include_tasks:
    file: api_server/main.yml
    apply:
      tags: api_server

- name: Setup Kubernetes controller manager
  tags: controller_manager
  ansible.builtin.include_tasks:
    file: controller_manager/main.yml
    apply:
      tags: controller_manager
