---
- name: Download Kubernetes
  tags: download
  ansible.builtin.include_tasks:
    file: download.yml
    apply:
      tags: download
      become: false
      run_once: true
      delegate_to: localhost

- name: Install Kubernetes
  tags: install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: install

- name: Create Kubernetes certificates
  tags: cert
  ansible.builtin.include_tasks:
    file: cert.yml
    apply:
      tags: cert
      become: false
      delegate_to: localhost

- name: Setup Kubernetes API server
  tags: api_server
  block:
    - name: Create Kubernetes API server certificates
      tags: cert
      ansible.builtin.include_tasks:
        file: api_server/cert.yml
        apply:
          tags:
            - cert
            - api_server
          become: false
          delegate_to: localhost

    - name: Configure Kubernetes API server
      tags: config
      ansible.builtin.include_tasks:
        file: api_server/config.yml
        apply:
          tags:
            - config
            - api_server
          notify:
            - Reload SystemD daemon
            - Enable Kubernetes API server service
            - Restart Kubernetes API server service

- name: Setup Kubernetes controller manager
  tags: controller_manager
  block:
    - name: Create Kubernetes controller manager certificates
      tags: cert
      ansible.builtin.include_tasks:
        file: controller_manager/cert.yml
        apply:
          tags:
            - cert
            - controller_manager
          become: false
          delegate_to: localhost

    - name: Configure Kubernetes controller manager
      tags: config
      ansible.builtin.include_tasks:
        file: controller_manager/config.yml
        apply:
          tags:
            - config
            - controller_manager
          notify:
            - Reload SystemD daemon
            - Enable Kubernetes controller manager service
            - Restart Kubernetes controller manager service

- name: Setup Kubernetes scheduler
  tags: scheduler
  block:
    - name: Create Kubernetes scheduler certificates
      ansible.builtin.include_tasks:
        file: scheduler/cert.yml
        apply:
          tags:
            - cert
            - scheduler
          become: false
          delegate_to: localhost

    - name: Configure Kubernetes scheduler
      ansible.builtin.include_tasks:
        file: scheduler/config.yml
        apply:
          tags:
            - config
            - scheduler
          notify:
            - Reload SystemD daemon
            - Enable Kubernetes scheduler service
            - Restart Kubernetes scheduler service

- name: Setup Kubelet
  tags: kubelet
  block:
    - name: Create Kubelet certificates
      ansible.builtin.include_tasks:
        file: kubelet/cert.yml
        apply:
          tags:
            - cert
            - kubelet
          become: false
          delegate_to: localhost

    - name: Configure Kubelet
      ansible.builtin.include_tasks:
        file: kubelet/config.yml
        apply:
          tags:
            - config
            - kubelet
          notify:
            - Reload SystemD daemon
            - Enable Kubelet service
            - Restart Kubelet service

- name: Setup Kubernetes proxy
  tags: proxy
  block:
    - name: Create Kubernetes proxy certificates
      ansible.builtin.include_tasks:
        file: proxy/cert.yml
        apply:
          tags:
            - cert
            - proxy
          become: false
          delegate_to: localhost

    - name: Configure Kubernetes proxy
      ansible.builtin.include_tasks:
        file: proxy/config.yml
        apply:
          tags:
            - config
            - proxy
          notify:
            - Reload SystemD daemon
            - Enable Kubernetes proxy service
            - Restart Kubernetes proxy service
