---
- name: Download Kubernetes
  tags: download
  become: false
  run_once: true
  delegate_to: localhost
  ansible.builtin.import_tasks: download.yml

- name: Install Kubernetes
  tags: install
  ansible.builtin.import_tasks: install.yml
