---
# Version of CNI plugins to download. Can be a specific version (e.g., "1.1.12") or "latest".
container_runtime_cni_plugins_download_version: latest

# URL to download the CNI plugins archive, constructed from GitHub user, repository, version, and architecture.
container_runtime_cni_plugins_download_url: "https://github.com/{{ container_runtime_cni_plugins_download_github_user }}/{{ container_runtime_cni_plugins_download_github_repository }}/releases/download/v{{ container_runtime_cni_plugins_download_version }}/cni-plugins-linux-{{ container_runtime_cni_plugins_download_architecture[1] }}-v{{ container_runtime_cni_plugins_download_version }}.tgz"
