---
# GitHub user or organization that maintains the runc repository.
container_runtime_runc_download_github_user: opencontainers

# GitHub repository name for runc.
container_runtime_runc_download_github_repository: runc

# Mapping from system architecture to runc release architecture naming.
container_runtime_runc_download_architecture_map:
  x86_64: amd64
  aarch64: arm64

# Local directory path where the runc binary will be downloaded.
container_runtime_runc_download_dir: "{{ playbook_dir }}/../.download/runc"
