---
# GitHub user or organization that maintains the runc repository.
container_runtime_runc_download_github_user: opencontainers

# GitHub repository name for runc.
container_runtime_runc_download_github_repository: runc

# Mapping from system architecture to runc release architecture naming.
container_runtime_runc_download_architecture_map:
  x86_64: amd64
  aarch64: arm64

# Directory path where specific versions of runc will be downloaded.
container_runtime_runc_download_local_dir: "{{ role_path }}/../container_runtime/files/runc/download/"

# Symlink path pointing to the currently used runc version.
container_runtime_runc_download_current_local_dir_link: "{{ (container_runtime_runc_download_local_dir, 'current') | ansible.builtin.path_join }}"
