---
# Base local directory for storing Kubernetes controller manager certificates.
kubernetes_controller_manager_cert_local_dir: "{{ role_path }}/../kubernetes/files/controller_manager/cert/{{ inventory_dir | ansible.builtin.basename }}"

# Directory for storing Kubernetes controller manager entity (host) certificate and key files.
kubernetes_controller_manager_cert_entity_local_dir: "{{ (kubernetes_controller_manager_cert_local_dir, 'entity') | ansible.builtin.path_join }}"
