---
# Directory where Kubernetes controller manager configuration files will be stored.
kubernetes_controller_manager_config_dir: "{{ (kubernetes_config_dir, 'controller-manager') | ansible.builtin.path_join }}"

# File where Kubernetes controller manager Kubeconfig will be stored.
kubernetes_controller_manager_config_path: "{{ (kubernetes_controller_manager_config_dir, 'kubeconfig') | ansible.builtin.path_join }}"

# Directory where Kubernetes controller manager certificate files will be stored in the config path.
kubernetes_controller_manager_config_cert_dir: "{{ (kubernetes_controller_manager_config_dir, 'certs') | ansible.builtin.path_join }}"

# Directory where Kubernetes controller managerCAcertificate files will be stored in the config path.
kubernetes_controller_manager_config_cert_ca_dir: "{{ (kubernetes_controller_manager_config_cert_dir, 'ca') | ansible.builtin.path_join }}"

# Directory where Kubernetes controller manager entity certificate files will be stored in the config path.
kubernetes_controller_manager_config_cert_entity_dir: "{{ (kubernetes_controller_manager_config_cert_dir, 'entity') | ansible.builtin.path_join }}"

# Path to the Kubernetes controller manager service binary.
kubernetes_controller_manager_config_service_binary_file: "{{ (kubernetes_install_binaries_archive_extract_dir, 'kube-controller-manager') | ansible.builtin.path_join }}"
