---
# Nebula configuration.
nebula_config:
  # Host and port where the Nebula service listens for incoming traffic.
  listen:
    host: 0.0.0.0
    port: 4646

  # Configuration related to Nebula lighthouse functionality.
  lighthouse:
    am_lighthouse: true
    hosts: []

  # Name of the TUN interface created by Nebula.
  tun:
    dev: nebula0

  # Default firewall actions and rules for Nebula traffic.
  firewall:
    inbound_action: drop
    outbound_action: drop

    inbound:
      - host: any
        port: any
        proto: any

    outbound:
      - host: any
        port: any
        proto: any

  # Configuration for UDP hole punching support.
  punchy:
    punch: true
    respond: true

  # Settings for enabling or using relay nodes in Nebula.
  relay:
    am_relay: false
    use_relays: true
