---
# Directory for storing Kubernetes proxy entity (host) certificate and key files.
kubernetes_proxy_cert_entity_local_dir: "{{ (kubernetes_cert_entity_local_dir, 'proxy') | ansible.builtin.path_join }}"
