---
# GitHub user or organization that maintains the containerd repository.
container_runtime_containerd_download_github_user: containerd

# GitHub repository name for containerd.
container_runtime_containerd_download_github_repository: containerd

# Mapping from system architecture to containerd release architecture naming.
container_runtime_containerd_download_architecture_map:
  x86_64: amd64
  aarch64: arm64

# Directory path where specific versions of containerd will be downloaded.
container_runtime_containerd_download_local_dir: "{{ role_path }}/../container_runtime/files/containerd/download/"

# Symlink path pointing to the currently used containerd version.
container_runtime_containerd_download_current_local_dir_link: "{{ (container_runtime_containerd_download_local_dir, 'current') | ansible.builtin.path_join }}"
