---
# The Vagrant box image to use for all virtual machines.
box: generic/debian12

# Total number of virtual machines (nodes) to create.
nodes: 3

# Default hardware configuration for each VM.
domain:
  # Number of virtual CPU cores assigned to each VM.
  cores: 4

  # Amount of memory (in megabytes) assigned to each VM.
  memory: 2048

# Network configuration shared across all VMs.
network:
  # Port forwarding rules from host to guest.
  # Host ports will increment based on the VM index (e.g., 2231, 2232, 2233...).
  ports:
    # SSH port forwarding configuration.
    ssh:
      # Base host port to be forwarded.
      host: 2230
      # Guest port inside the VM to map to.
      guest: 22
