---
- name: Download containerd
  tags: download
  become: false
  run_once: true
  delegate_to: localhost
  ansible.builtin.import_tasks: download.yml

- name: Install containerd
  tags: install
  ansible.builtin.import_tasks: install.yml

- name: Configure containerd
  tags: config
  notify:
    - Reload SystemD daemon
    - Enable containerd service
    - Restart containerd service
  ansible.builtin.import_tasks: config.yml
