---
- name: Download containerd
  tags: download
  ansible.builtin.include_tasks:
    file: download.yml
    apply:
      tags: download
      become: false
      run_once: true
      delegate_to: localhost

- name: Install containerd
  tags: install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: install

- name: Configure containerd
  tags: config
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags: config
      notify:
        - Reload SystemD daemon
        - Enable containerd service
        - Restart containerd service
