---
- name: Install containerd service
  notify:
    - Reload SystemD daemon
    - Enable containerd service
    - Restart containerd service
  ansible.builtin.template:
    src: etc/systemd/system/containerd.service.j2
    dest: /etc/systemd/system/containerd.service
    mode: "0644"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
