---
- name: Download runc
  tags: download
  ansible.builtin.include_tasks:
    file: download.yml
    apply:
      tags: download
      become: false
      run_once: true
      delegate_to: localhost

- name: Install runc
  tags: install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: install
