---
# Version of Kubernetes to download. Can be a specific version (e.g., "1.1.12") or "latest".
kubernetes_download_version: latest

# URL to download the Kubernetes binary, constructed from GitHub user, repository, version, and architecture.
kubernetes_download_url: "https://dl.k8s.io/v{{ kubernetes_download_version }}/kubernetes-server-linux-{{ kubernetes_download_architecture[1] }}.tar.gz"
