---
# Subject details for the Kubelet certificate.
kubernetes_kubelet_cert_entity_subject:
  CN: system:node:{{ inventory_hostname }}
  O: system:nodes

# Subject Alternative Names for the Kubelet certificate.
kubernetes_kubelet_cert_entity_san:
  # Local
  - IP:127.0.0.1
  - DNS:localhost

  # Node
  - IP:{{ nebula_cert_entity_host_ip | ansible.utils.ipaddr('address') }}

  # DNS
  - DNS:{{ inventory_hostname }}

# Duration of Kubelet certificate validity.
kubernetes_kubelet_cert_entity_duration: 1825d
