---
# Kubelet API server address.
kubernetes_kubelet_config_server: https://{{ nebula_cert_entity_host_ip | ansible.utils.ipaddr('address') }}:6443

# Kubelet configuration.
kubernetes_kubelet_config:
  address: "{{ nebula_cert_entity_host_ip | ansible.utils.ipaddr('address') }}"
  port: 10250
  cgroupDriver: systemd
  containerRuntimeEndpoint: "unix:///var/run/containerd/containerd.sock"
  authentication:
    anonymous:
      enabled: false
    webhook:
      enabled: true
    x509:
      clientCAFile: "{{ (kubernetes_kubelet_config_cert_ca_dir, 'kubernetes.crt') | ansible.builtin.path_join }}"
  authorization:
    mode: Webhook

# Kubelet configuration flags.
kubernetes_kubelet_config_flags: --config={{ kubernetes_kubelet_config_path }}
  --kubeconfig={{ kubernetes_kubelet_config_kubeconfig_path }}
  --node-ip={{ nebula_cert_entity_host_ip | ansible.utils.ipaddr('address') }}
  --hostname-override={{ inventory_hostname }}
  --pod-cidr=10.244.0.0/16
