---
- name: Download CNI plugins
  tags: download
  ansible.builtin.include_tasks:
    file: download.yml
    apply:
      tags: download
      become: false
      run_once: true
      delegate_to: localhost

- name: Install CNI plugins
  tags: install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: install

- name: Configure CNI plugins
  tags: config
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags: config
