---
# Kubernetes controller manager API server address.
kubernetes_controller_manager_config_server: https://{{ nebula_cert_entity_host_ip | ansible.utils.ipaddr('address') }}:6443

# Kubernetes controller manager configuration flags.
kubernetes_controller_manager_config_flags:
  --bind-address={{ nebula_cert_entity_host_ip | ansible.utils.ipaddr('address') }}
  --secure-port=10257
  --cluster-cidr=10.200.0.0/16
  --cluster-name=kubernetes
  --root-ca-file={{ (kubernetes_controller_manager_config_cert_ca_dir, 'kubernetes.crt') | ansible.builtin.path_join }}
  --service-account-private-key-file={{ (kubernetes_controller_manager_config_cert_entity_dir, 'service-account.key') | ansible.builtin.path_join }}
  --kubeconfig={{ kubernetes_controller_manager_config_path }}
  --service-cluster-ip-range=10.32.0.0/24
  --use-service-account-credentials=true
