---
- name: Create Kubernetes scheduler directories
  loop:
    - path: "{{ kubernetes_scheduler_config_dir }}"
      mode: "0755"
    - path: "{{ kubernetes_scheduler_config_cert_dir }}"
      mode: "0755"
    - path: "{{ kubernetes_scheduler_config_cert_ca_dir }}"
      mode: "0755"
    - path: "{{ kubernetes_scheduler_config_cert_entity_dir }}"
      mode: "0700"
  loop_control:
    label: "{{ item.path }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    state: directory
    owner: root
    group: root

- name: Copy scheduler certificates
  loop:
    - label: Kubernetes CA certificate
      src: "{{ (kubernetes_cert_ca_local_dir, 'ca.crt') | ansible.builtin.path_join }}"
      dest: "{{ (kubernetes_scheduler_config_cert_ca_dir, 'kubernetes.crt') | ansible.builtin.path_join }}"
      mode: "0644"
    - label: Kubernetes scheduler certificate
      src: "{{ (kubernetes_scheduler_cert_entity_local_dir, inventory_hostname, 'scheduler.crt') | ansible.builtin.path_join }}"
      dest: "{{ (kubernetes_scheduler_config_cert_entity_dir, 'scheduler.crt') | ansible.builtin.path_join }}"
      mode: "0644"
    - label: Kubernetes scheduler private key
      src: "{{ (kubernetes_scheduler_cert_entity_local_dir, inventory_hostname, 'scheduler.key') | ansible.builtin.path_join }}"
      dest: "{{ (kubernetes_scheduler_config_cert_entity_dir, 'scheduler.key') | ansible.builtin.path_join }}"
      mode: "0600"
  loop_control:
    label: "{{ item.label }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root

- name: Create Kubernetes scheduler Kubeconfig
  block:
    - name: Create temporary file
      register: kubernetes_scheduler_config_tempfile
      changed_when: false
      ansible.builtin.tempfile:
        state: file

    - name: Write temporary Kubernetes scheduler Kubeconfig
      environment:
        KUBECONFIG: "{{ kubernetes_scheduler_config_tempfile.path }}"
      block:
        - name: Set cluster for Kubernetes scheduler
          changed_when: false
          ansible.builtin.command:
            argv:
              - kubectl
              - config
              - set-cluster
              - default
              - --server={{ kubernetes_scheduler_config_server }}
              - --certificate-authority={{ (kubernetes_scheduler_config_cert_ca_dir, 'kubernetes.crt') | ansible.builtin.path_join }}

        - name: Set credentials for Kubernetes scheduler
          changed_when: false
          ansible.builtin.command:
            argv:
              - kubectl
              - config
              - set-credentials
              - scheduler
              - --client-key={{ (kubernetes_scheduler_config_cert_entity_dir, 'scheduler.key') | ansible.builtin.path_join }}
              - --client-certificate={{ (kubernetes_scheduler_config_cert_entity_dir, 'scheduler.crt') | ansible.builtin.path_join }}

        - name: Set context for Kubernetes scheduler
          changed_when: false
          ansible.builtin.command:
            argv:
              - kubectl
              - config
              - set-context
              - default
              - --user=scheduler
              - --cluster=default

        - name: Use context for Kubernetes scheduler
          changed_when: false
          ansible.builtin.command:
            argv:
              - kubectl
              - config
              - use-context
              - default

    - name: Write Kubeconfig for Kubernetes scheduler
      ansible.builtin.copy:
        src: "{{ kubernetes_scheduler_config_tempfile.path }}"
        dest: "{{ kubernetes_scheduler_config_kubeconfig_path }}"
        mode: "0644"
        owner: root
        group: root
        remote_src: true

    - name: Delete temporary Kubeconfig for Kubernetes scheduler
      changed_when: false
      ansible.builtin.file:
        path: "{{ kubernetes_scheduler_config_tempfile.path }}"
        state: absent

- name: Render config for Kubernetes scheduler
  ansible.builtin.template:
    src: scheduler/scheduler.yml.j2
    dest: "{{ kubernetes_scheduler_config_path }}"
    mode: "0644"

- name: Install Kubernetes scheduler service
  ansible.builtin.template:
    src: scheduler/kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
    mode: "0644"
