---
- name: Reload SystemD daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable Kubernetes API server service
  ansible.builtin.systemd_service:
    name: kubernetes-api-server
    enabled: true

- name: Restart Kubernetes API server service
  ansible.builtin.systemd_service:
    name: kubernetes-api-server
    state: restarted
