---
- name: Reload SystemD daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable Kubernetes API server service
  ansible.builtin.systemd_service:
    name: kube-apiserver
    enabled: true

- name: Restart Kubernetes API server service
  ansible.builtin.systemd_service:
    name: kube-apiserver
    state: restarted

- name: Enable Kubernetes controller manager service
  ansible.builtin.systemd_service:
    name: kube-controller-manager
    enabled: true

- name: Restart Kubernetes controller manager service
  ansible.builtin.systemd_service:
    name: kube-controller-manager
    state: restarted

- name: Enable Kubernetes scheduler service
  ansible.builtin.systemd_service:
    name: kube-scheduler
    enabled: true

- name: Restart Kubernetes scheduler service
  ansible.builtin.systemd_service:
    name: kube-scheduler
    state: restarted

- name: Enable Kubelet service
  ansible.builtin.systemd_service:
    name: kubelet
    enabled: true

- name: Restart Kubelet service
  ansible.builtin.systemd_service:
    name: kubelet
    state: restarted

- name: Enable Kubernetes proxy service
  ansible.builtin.systemd_service:
    name: kube-proxy
    enabled: true

- name: Restart Kubernetes proxy service
  ansible.builtin.systemd_service:
    name: kube-proxy
    state: restarted
