---
- name: Reload SystemD daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable Kubernetes API server service
  ansible.builtin.systemd_service:
    name: kubernetes-api-server
    enabled: true

- name: Restart Kubernetes API server service
  ansible.builtin.systemd_service:
    name: kubernetes-api-server
    state: restarted

- name: Enable Kubernetes controller manager service
  ansible.builtin.systemd_service:
    name: kubernetes-controller-manager
    enabled: true

- name: Restart Kubernetes controller manager service
  ansible.builtin.systemd_service:
    name: kubernetes-controller-manager
    state: restarted

- name: Enable Kubernetes scheduler service
  ansible.builtin.systemd_service:
    name: kubernetes-scheduler
    enabled: true

- name: Restart Kubernetes scheduler service
  ansible.builtin.systemd_service:
    name: kubernetes-scheduler
    state: restarted
