---
# Base local directory for storing Kubernetes scheduler certificates.
kubernetes_scheduler_cert_local_dir: "{{ role_path }}/../kubernetes/files/scheduler/cert/{{ inventory_dir | ansible.builtin.basename }}"

# Directory for storing Kubernetes scheduler entity (host) certificate and key files.
kubernetes_scheduler_cert_entity_local_dir: "{{ (kubernetes_scheduler_cert_local_dir, 'entity') | ansible.builtin.path_join }}"
