---
# Local path to the downloaded etcd binaries archive for the current architecture.
etcd_install_binaries_archive_local_file: "{{ (etcd_download_current_local_dir_link, ansible_architecture) | ansible.builtin.path_join }}"

# Destination path on the target system where the etcd will be installed.
etcd_install_binaries_archive_extract_dir: /usr/local/bin/

# Additional options for extracting the etcd archive.
etcd_install_binaries_unarchive_options: [--strip-components=1, --wildcards]

# List of file or directory patterns to include when extracting the archive.
etcd_install_binaries_unarchive_include: ["*/etcd"]
