---
name: Run Ansible Lint

on:
  push:
    paths:
      - infrastructure/ansible/**
      - .github/workflows/ansible-lint.yml
    branches:
      - main

  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python interpreter
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Run Ansible Lint
        run: |
          pip install -r requirements.txt
          ansible-lint
        working-directory: infrastructure/ansible
