---
name: Run Ansible Lint

on:
  push:
    paths:
      - infrastructure/ansible/**
      - .github/workflows/ansible-lint.yml
    branches:
      - main

  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: infrastructure/ansible
